### ISSUE TITLE
May 7th Gatsby Event with Web Performance Group

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/jamstack.nyc#3]
## Event Description
- [x] List Speakers, with Twitter handle
- [x] Outline topics

## Venue
- [ ] Venue name
- [ ] Special requirements
- [ ] List venue contacts

## Food & Beverage 
- [ ] Catering option

## Technical
- [ ] Videography

## Sponsors
- [ ] Send Shy details. Contentful will sponsor

**Comment by budparr** [comment]
https://www.meetup.com/JAMstack-nyc/events/259420382/
